engineStrict: true

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - mongodb-memory-server

sideEffectsCache: false

verifyDepsBeforeRun: prompt
